#ifndef TQ_GUC_H
#define TQ_GUC_H

extern int tq_guc_probes;
extern int tq_guc_oversample_factor;
extern int tq_guc_max_visited_codes;
extern int tq_guc_max_visited_pages;
extern int tq_guc_iterative_scan;
extern int tq_guc_min_rows_after_filter;
extern int tq_guc_delta_merge_live_count_threshold;
extern int tq_guc_delta_merge_page_count_threshold;
extern int tq_guc_delta_merge_live_percent_threshold;
extern int tq_guc_maintenance_dead_tuple_percent_threshold;
extern int tq_guc_maintenance_reclaimable_page_threshold;
extern int tq_guc_decode_rescore_factor;
extern int tq_guc_decode_rescore_extra_candidates;
extern bool tq_guc_enable_summary_bounds;
extern bool tq_guc_shadow_decode_diagnostics;
extern bool tq_guc_force_decode_score_diagnostics;

#endif
